sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - usermod -a -G dialout $USER &&  apt-get install git &&  wget https://bootstrap.pypa.io/get-pip.py &&  python get-pip.py &&  pip install pyserial &&  mkdir -p ~/Arduino/hardware/espressif &&  cd ~/Arduino/hardware/espressif &&  git clone https://github.com/espressif/arduino-esp32.git esp32 &&  cd esp32 &&  git submodule update --init --recursive &&  cd tools &&  python2 get.py

script:
  - ./run_test.sh

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
